# Précharger l'image en mémoire (Obligatoire)
preload = /home/jorisgriaud/Images/Wallpapers/15691982.jpg
preload = /home/jorisgriaud/Images/Wallpapers/15692055.jpg

# Assigner l'image à tous les écrans (en laissant vide après la virgule)
# Assigner spécifiquement par écran
wallpaper = DP-1,/home/jorisgriaud/Images/Wallpapers/15691982.jpg
wallpaper = HDMI-A-1,/home/jorisgriaud/Images/Wallpapers/15692055.jpg

splash = false